version: "3.9"

services:
  redis:
    image: redis:latest
    container_name: redis
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb
    platform: linux/amd64
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

volumes:
  redis_data:
  timescale_data:
